---

name: Simon Constans
language_code: fr
exclude:
  - bower_components
  - node_modules
  - src
  - .gitignore
  - bower.json
  - Gemfile
  - Gemfile.lock
  - gulpfile.coffee
  - package.json
  - README.md
